## https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/ ##

# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages: [ icu4c ]
      compiler: clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && cmake --build . --config Release
  - ctest -C Release -V
